### ISSUE TITLE
I'm interested in your project, noob help!

### ISSUE THREAD

**Issue by naziko2411** [mmjee/instagram-story-robot#3]
Hello there! I'm interested in your Instagram story repository and I want to see their every story as I saw on the code and it's the only repository that uses every Instagram stories I've found but I'm a noob for this project. I have Visual Studio Code, can you show me how to use it?

**Comment by mmjee** [comment]
@naziko2411 I'm really, really sorry about the extremely late response (somehow GitHub never notified me of this), do you want to watch the stories (as of now it just saves the stories to disk)? 

(In cases like these it's probably better to email me instead of creating a issue)

**Comment by naziko2411** [comment]
Yes, but how?

**Comment by mmjee** [comment]
> Yes, but how?

Once downloaded, you can open the folder where it's saved ([extend function from here](https://github.com/mmjee/instagram-story-robot/blob/master/isr/instagram/index.js#L44)) automatically or manually.

**Comment by naziko2411** [comment]
Thanks
